# File: KnobStudio_Linux.py
# Version: 7.1 (Linux Edition)
# Author: Stylianos Tanellari


import os
import sys
import grp
import pwd
import time
import json
import threading
import serial
import serial.tools.list_ports
import psutil


try:
    import tkinter as tk
    from tkinter import messagebox
except (ModuleNotFoundError, Exception) as _tk_err:
    print(
        f"\nERROR: Cannot initialise Tkinter display.\n"
        f"  {_tk_err}\n\n"
        f"  This tool requires a graphical desktop environment (X11 or Wayland).\n"
        f"  If running over SSH, try: ssh -X user@host\n"
        f"  To install Tkinter on Debian/Ubuntu: sudo apt install python3-tk\n",
        file=sys.stderr
    )
    sys.exit(1)

try:
    import customtkinter as ctk
except Exception as e:
    import tkinter.messagebox as _mb
    _mb.showerror(
        "Missing dependency",
        "CustomTkinter is not installed.\n\n"
        "    pip install customtkinter\n\n" + str(e)
    )
    sys.exit(1)


# Constants

AVAILABLE_SIMPLE_ACTIONS = [
    "nothing",
    "volume_up", "volume_down", "mute", "play_pause", "next_track", "prev_track",
    "scroll_up", "scroll_down", "undo", "redo",
    "mouse_move_x_pos", "mouse_move_x_neg", "mouse_move_y_pos", "mouse_move_y_neg",
    "mouse_scroll_v_pos", "mouse_scroll_v_neg", "mouse_scroll_h_pos", "mouse_scroll_h_neg",
    "mouse_click_left", "mouse_click_right", "mouse_click_middle",
    "next_profile", "switch_profile_1", "switch_profile_2", "switch_profile_3",
]

MODIFIER_DISPLAY_MAP = {
    "LEFT_CONTROL":  "Ctrl",    "LEFT_SHIFT":  "Shift",
    "LEFT_ALT":      "Alt",     "LEFT_GUI":    "Win/Cmd",
    "RIGHT_CONTROL": "RCtrl",   "RIGHT_SHIFT": "RShift",
    "RIGHT_ALT":     "RAlt",    "RIGHT_GUI":   "RWin",
}

_ALL_GESTURE_KEYS = (
    "cw", "ccw", "click", "double_click", "triple_click",
    "long_press", "cw_shifted", "ccw_shifted",
)


# Helpers

def normalize_key_name(key_str):
    key = key_str.strip().upper()
    aliases = {
        "CONTROL": "LEFT_CONTROL", "CTRL":    "LEFT_CONTROL",
        "SHIFT":   "LEFT_SHIFT",
        "ALT":     "LEFT_ALT",     "ALT_GR":  "LEFT_ALT",
        "WIN":     "LEFT_GUI",     "CMD":     "LEFT_GUI",
        "WINDOWS": "LEFT_GUI",     "COMMAND": "LEFT_GUI",
        "WIN/CMD": "LEFT_GUI",     "WIN/COMMAND": "LEFT_GUI",
        "DEL":     "DELETE",       "ESC":     "ESCAPE",
        "UP":      "UP_ARROW",     "DOWN":    "DOWN_ARROW",
        "LEFT":    "LEFT_ARROW",   "RIGHT":   "RIGHT_ARROW",
    }
    return aliases.get(key, key)


# Linux-specific: CIRCUITPY drive detection

def find_circuitpy_drive():
    """
    Returns the mount point of the CIRCUITPY drive, or None if not found.

    Strategy (tried in order for each readable mounted partition):
      1. Mount path contains 'CIRCUITPY' — catches Fedora/KDE automounts at
         /run/media/<user>/CIRCUITPY immediately.
      2. Filesystem probe — the partition contains BOTH 'boot_out.txt' AND
         'code.py'. Requiring both files reduces false-positive matches against
         arbitrary USB drives that happen to contain a code.py at their root.
         boot_out.txt is generated by CircuitPython on every boot and is
         effectively unique to those devices. [FLAW-2 FIX]
    """
    for part in psutil.disk_partitions(all=True):
        if not part.mountpoint or not part.fstype:
            continue
        if "ro" in part.opts.split(","):
            continue
        mp = part.mountpoint
        try:
            if "CIRCUITPY" in mp.upper():
                return mp
            if (os.path.exists(os.path.join(mp, "boot_out.txt")) and
                    os.path.exists(os.path.join(mp, "code.py"))):
                return mp
        except (PermissionError, OSError):
            continue
    return None


# Linux-specific: serial port detection

def find_pico_serial_port_for_reboot():
    """
    Returns the device path (e.g. /dev/ttyACM0) of the Pico's data serial
    port, or None if not found.

    Detection passes (in order):
      1. Exact USB VID (0x2E8A) + PID (0x000A) match — most reliable.
      2. Raspberry Pi VID with a Pico/CircuitPython/CDC description keyword.
      3. Any /dev/ttyACM* port whose VID matches or is unknown — last resort.
    """
    VID = 0x2E8A
    PID = 0x000A

    for port in serial.tools.list_ports.comports():
        if port.vid == VID and getattr(port, "pid", None) == PID:
            return port.device

    for port in serial.tools.list_ports.comports():
        if port.vid == VID:
            desc = port.description or ""
            if any(k in desc for k in ("Pico", "CircuitPython", "CDC")):
                return port.device

    for port in serial.tools.list_ports.comports():
        if port.device.startswith("/dev/ttyACM"):
            if port.vid == VID or port.vid is None:
                return port.device

    return None


# Linux-specific: dialout group check

def check_dialout_group():
    """Returns True if the current user belongs to the 'dialout' group."""
    try:
        username    = os.environ.get("USER") or os.environ.get("LOGNAME") or ""
        dialout_gid = grp.getgrnam("dialout").gr_gid
        if pwd.getpwnam(username).pw_gid == dialout_gid:
            return True
        return username in grp.getgrnam("dialout").gr_mem
    except Exception:
        return False


def send_reboot_command(port_name):

    try:
        with serial.Serial(port_name, timeout=2, write_timeout=2) as s:
            s.write(b"\x03")        # Ctrl+C — interrupt running code.py
            time.sleep(0.15)        # wait for REPL to reach >>> prompt
            s.write(b"\x04")        # Ctrl+D — soft reboot
        return True
    except PermissionError:
        return "permission_error"
    except Exception as e:
        print(f"[REBOOT] {e}")
        return False


# Action Editor

class ActionEditor(ctk.CTkToplevel):

    def __init__(self, parent, current_action_obj, profile_num, action_key):
        super().__init__(parent)
        self.result = None

        self.title(f"Edit Action  —  Profile {profile_num}  /  {action_key.upper()}")
        self.geometry("450x450")
        self.transient(parent)
        self.wait_visibility()
        self.grab_set()
        self.resizable(False, False)
        self.protocol("WM_DELETE_WINDOW", self._on_cancel)

        self.tabs = ctk.CTkTabview(self, width=400, height=390)
        self.tabs.pack(pady=10, padx=10, fill="both", expand=True)
        self.tabs.add("Simple Action")
        self.tabs.add("Simple Macro")
        self.tabs.add("Adv. Macro (Sequence)")

        # Tab 1: Simple Action
        sf = self.tabs.tab("Simple Action")
        self.simple_tab_var = tk.StringVar()
        ctk.CTkLabel(sf, text="Select a simple HID action:").pack(anchor="w", padx=20, pady=(10, 5))
        ctk.CTkOptionMenu(sf, values=AVAILABLE_SIMPLE_ACTIONS,
                          variable=self.simple_tab_var, width=300).pack(anchor="w", padx=20, pady=5)

        # Tab 2: Simple Macro 
        mf = self.tabs.tab("Simple Macro")
        self.macro_entry_var = tk.StringVar()
        ctk.CTkLabel(mf, text="Enter key combination (e.g., CTRL+SHIFT+T):").pack(anchor="w", padx=20, pady=(10, 5))
        ctk.CTkEntry(mf, textvariable=self.macro_entry_var, width=300,
                     font=("Consolas", 13)).pack(anchor="w", padx=20, pady=5)
        ctk.CTkLabel(mf, text="Use this for simple, simultaneous key presses.").pack(anchor="w", padx=20, pady=5)
        ctk.CTkLabel(mf, text="Separate simultaneous keys with '+'.",
                     text_color="gray", font=("Arial", 10)).pack(anchor="w", padx=20)

        # Tab 3: Advanced Macro 
        af = self.tabs.tab("Adv. Macro (Sequence)")
        ctk.CTkLabel(af, text="Enter macro sequence (one command per line):").pack(anchor="w", padx=20, pady=(10, 5))
        self.adv_macro_textbox = ctk.CTkTextbox(af, width=360, height=200, font=("Consolas", 12))
        self.adv_macro_textbox.pack(anchor="w", padx=20, pady=5, fill="both", expand=True)
        ctk.CTkLabel(af, text="Commands: press, release, tap, wait (ms), release_all",
                     text_color="gray", font=("Arial", 10)).pack(anchor="w", padx=20, pady=(0, 5))

        bf = ctk.CTkFrame(self, fg_color="transparent")
        bf.pack(fill="x", padx=10, pady=(0, 10))
        ctk.CTkButton(bf, text="Save Action", command=self._on_save).pack(side="right", padx=10)
        ctk.CTkButton(bf, text="Cancel", command=self._on_cancel,
                      fg_color="gray").pack(side="right", padx=5)

        self._load_current_action(current_action_obj)

    def _load_current_action(self, action_obj):
        try:
            t = action_obj.get("type", "simple")
            if t == "macro_advanced":
                self.tabs.set("Adv. Macro (Sequence)")
                self.adv_macro_textbox.insert("1.0",
                    self._steps_to_script(action_obj.get("steps", [])))
            elif t == "macro":
                self.tabs.set("Simple Macro")
                keys = [MODIFIER_DISPLAY_MAP.get(k, k.upper()) for k in action_obj.get("keys", [])]
                self.macro_entry_var.set(" + ".join(keys))
            else:
                self.tabs.set("Simple Action")
                self.simple_tab_var.set(action_obj.get("action", "nothing"))
        except Exception as e:
            print(f"[ActionEditor] Load error: {e}")

    def _on_save(self):
        tab = self.tabs.get()

        if tab == "Simple Action":
            self.result = {"type": "simple", "action": self.simple_tab_var.get()}

        elif tab == "Simple Macro":
            raw = self.macro_entry_var.get().strip()
            if not raw:
                messagebox.showerror("Error", "Macro string is empty.", parent=self)
                return
            keys = [normalize_key_name(k) for k in raw.split("+") if k.strip()]
            if not keys:
                messagebox.showerror("Error", "Macro string is invalid.", parent=self)
                return
            self.result = {"type": "macro", "keys": keys}

        elif tab == "Adv. Macro (Sequence)":
            text = self.adv_macro_textbox.get("1.0", "end-1c")
            steps, error = self._script_to_steps(text)
            if error:
                messagebox.showerror("Macro Error", error, parent=self)
                return
            self.result = {"type": "macro_advanced", "steps": steps}

        self.grab_release()
        self.destroy()

    def _on_cancel(self):
        self.result = None
        self.grab_release()
        self.destroy()

    def _script_to_steps(self, script_text):
        steps = []
        for i, raw_line in enumerate(script_text.splitlines()):
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.lower().split(maxsplit=1)
            cmd  = parts[0]
            args = parts[1] if len(parts) > 1 else ""
            ln   = i + 1
            try:
                if cmd == "wait":
                    raw_ms = int(args)
                    if not (0 <= raw_ms <= 10_000):
                        return None, (
                            f"Line {ln}: 'wait' value must be 0–10000 ms "
                            f"(got {raw_ms}). Max is 10 seconds per step."
                        )
                    steps.append({"wait": raw_ms / 1000.0})
                elif cmd in ("press", "tap", "release"):
                    if not args:
                        return None, f"Line {ln}: '{cmd}' requires at least one key."
                    keys = [normalize_key_name(k) for k in args.split("+") if k.strip()]
                    if not keys:
                        return None, f"Line {ln}: invalid keys for '{cmd}'."
                    steps.append({cmd: keys})
                elif cmd == "release_all":
                    steps.append({"release_all": True})
                else:
                    return None, f"Line {ln}: unknown command '{cmd}'."
            except Exception as e:
                return None, f"Line {ln} ('{line}'): {e}"
        return steps, None

    def _steps_to_script(self, steps):
        lines = []
        for step in steps:
            try:
                if "wait" in step:
                    lines.append(f"wait {round(step['wait'] * 1000)}")
                elif "press" in step:
                    lines.append("press " + " + ".join(
                        MODIFIER_DISPLAY_MAP.get(k, k.upper()) for k in step["press"]))
                elif "tap" in step:
                    lines.append("tap " + " + ".join(
                        MODIFIER_DISPLAY_MAP.get(k, k.upper()) for k in step["tap"]))
                elif "release" in step:
                    lines.append("release " + " + ".join(
                        MODIFIER_DISPLAY_MAP.get(k, k.upper()) for k in step["release"]))
                elif step.get("release_all"):
                    lines.append("release_all")
            except Exception as e:
                lines.append(f"# ERROR: {step} ({e})")
        return "\n".join(lines)


# Main Configurator

class MultiKnobConfiguratorModern:

    def __init__(self, root):
        self.root = root
        self.root.title("KnobStudio — v7.0 (Linux Edition)")
        ctk.set_appearance_mode("Dark")

        try:
            ctk.set_default_color_theme("green")
        except Exception:
            pass
        
        self.root.geometry("1000x720")
        self.root.minsize(980, 720)
        self.profile_vars   = {}
        self.action_labels  = {}
        self.current_settings = self.load_gui_settings()
        self.main_frame = ctk.CTkFrame(root, corner_radius=8, fg_color="#0b1220")
        self.main_frame.pack(fill="both", expand=True, padx=12, pady=12)
        self.left = ctk.CTkFrame(self.main_frame)
        self.left.pack(side="left", fill="both", expand=True, padx=(8, 4), pady=8)
        self.right = ctk.CTkFrame(self.main_frame, width=260)
        self.right.pack(side="right", fill="y", padx=(4, 8), pady=8)
        self.build_left()
        self.build_right()
        self.bottom_bar()
        self.root.protocol("WM_DELETE_WINDOW", self.root.destroy)
        self.root.after(500, self._check_dialout_on_startup)

  
    def _check_dialout_on_startup(self):
        if not check_dialout_group():
            self.log_add("WARNING: Not in the 'dialout' group — serial reboot may fail.")
            self.log_add("  Fix:  sudo usermod -aG dialout $USER   (then log out/in)")
            self.set_status("Warning: not in dialout group")


    def build_left(self):
        ctk.CTkLabel(self.left, text="KnobStudio  [Linux]",
                     font=ctk.CTkFont(size=18, weight="bold")).pack(anchor="w", padx=14, pady=(10, 6))

        gf = ctk.CTkFrame(self.left)
        gf.pack(fill="x", padx=12, pady=(0, 10))
        gf.grid_columnconfigure(1, weight=1)
        gf.grid_columnconfigure(4, weight=1)

        def _slider_row(frame, grid_row, col_start, label, var, from_, to, steps):
            ctk.CTkLabel(frame, text=label).grid(row=grid_row, column=col_start,
                                                 padx=(8, 4), pady=8, sticky="w")
            lbl = ctk.CTkLabel(frame, width=28)
            lbl.grid(row=grid_row, column=col_start + 2, padx=(0, 12))
            ctk.CTkSlider(frame, from_=from_, to=to, number_of_steps=steps, variable=var,
                          command=lambda v, l=lbl: l.configure(text=f"{int(v)}x")
                          ).grid(row=grid_row, column=col_start + 1, padx=(0, 8), pady=8, sticky="ew")
            lbl.configure(text=f"{var.get()}x")

        self.sens_vol   = tk.IntVar(value=self.current_settings.get("sensitivity_volume", 2))
        self.sens_scr   = tk.IntVar(value=self.current_settings.get("sensitivity_scroll", 1))
        self.sens_mouse = tk.IntVar(value=self.current_settings.get("sensitivity_mouse",  4))

        _slider_row(gf, 0, 0, "Volume Sens:", self.sens_vol,   2, 10, 8)
        _slider_row(gf, 0, 3, "Kbd Scroll:",  self.sens_scr,   1, 10, 9)

        ctk.CTkLabel(gf, text="Mouse Sens:").grid(row=1, column=0, padx=(8, 4), pady=8, sticky="w")
        mouse_lbl = ctk.CTkLabel(gf, width=28)
        mouse_lbl.grid(row=1, column=5, padx=(0, 12))
        ctk.CTkSlider(gf, from_=1, to=10, number_of_steps=9, variable=self.sens_mouse,
                      command=lambda v: mouse_lbl.configure(text=f"{int(v)}x")
                      ).grid(row=1, column=1, columnspan=4, padx=(0, 8), pady=8, sticky="ew")
        mouse_lbl.configure(text=f"{self.sens_mouse.get()}x")

        self.tabs = ctk.CTkTabview(self.left)
        self.tabs.pack(fill="both", expand=True, padx=12, pady=8)

        for i in (1, 2, 3):
            self.tabs.add(f"Profile {i}")
            tab = self.tabs.tab(f"Profile {i}")
            tab.grid_columnconfigure(1, weight=1)
            tab.grid_columnconfigure(2, weight=0)

            self.profile_vars[i] = self.current_settings.get(f"profile{i}", {
                k: {"type": "simple", "action": "nothing"} for k in _ALL_GESTURE_KEYS
            })
            self.action_labels[i] = {}

            rows = [
                ("Clockwise (CW):",   "cw",           False),
                ("Counter-CW (CCW):", "ccw",          False),
                ("Click:",            "click",        False),
                ("Double Click:",     "double_click", False),
                ("Triple Click:",     "triple_click", False),
                ("Long Press:",       "long_press",   False),
                ("Hold + CW:",        "cw_shifted",   True),
                ("Hold + CCW:",       "ccw_shifted",  True),
            ]
            for row, (label, key, is_new) in enumerate(rows):
                self._profile_row(tab, i, label, key, row, is_new=is_new)

        self.tabs.set("Profile 1")

    def _profile_row(self, tab, profile_index, label_text, action_key, row, is_new=False):
        pady = (12 if is_new else (10 if row == 0 else 8), 8)
        ctk.CTkLabel(tab, text=label_text).grid(row=row, column=0, sticky="w", padx=10, pady=pady)
        self.profile_vars[profile_index].setdefault(
            action_key, {"type": "simple", "action": "nothing"})
        action_obj  = self.profile_vars[profile_index][action_key]
        display_lbl = ctk.CTkLabel(tab, text=self._action_display_text(action_obj),
                                   anchor="e", font=ctk.CTkFont(family="Consolas", size=13))
        display_lbl.grid(row=row, column=1, padx=10, pady=pady, sticky="ew")
        self.action_labels[profile_index][action_key] = display_lbl
        ctk.CTkButton(tab, text="Edit Action...", width=120,
                      command=lambda p=profile_index, k=action_key: self.open_action_editor(p, k)
                      ).grid(row=row, column=2, sticky="e", padx=10, pady=pady)

    def _action_display_text(self, action_obj):
        try:
            t = action_obj.get("type", "simple")
            if t == "macro_advanced":
                return "Macro: [Advanced Sequence]"
            if t == "macro":
                keys = [MODIFIER_DISPLAY_MAP.get(k, k.upper()) for k in action_obj.get("keys", [])]
                return "Macro: " + " + ".join(keys)
            return action_obj.get("action", "nothing")
        except Exception:
            return "Error"

    def open_action_editor(self, profile_index, action_key):
        editor = ActionEditor(self.root, self.profile_vars[profile_index][action_key],
                              profile_index, action_key)
        self.root.wait_window(editor)
        if editor.result:
            self.profile_vars[profile_index][action_key] = editor.result
            self.action_labels[profile_index][action_key].configure(
                text=self._action_display_text(editor.result))

    def build_right(self):
        ctk.CTkLabel(self.right, text="Control & Status",
                     font=ctk.CTkFont(size=14, weight="bold")).pack(pady=(10, 6))

        qf = ctk.CTkFrame(self.right)
        qf.pack(fill="x", padx=10, pady=(4, 8))
        self.refresh_btn = ctk.CTkButton(qf, text="Find CIRCUITPY", command=self.refresh_thread)
        self.refresh_btn.pack(fill="x", padx=10, pady=8)
        self.reboot_port_label = ctk.CTkLabel(qf, text="Reboot port: --", anchor="w")
        self.reboot_port_label.pack(fill="x", padx=10, pady=(0, 8))

        lf = ctk.CTkFrame(self.right)
        lf.pack(fill="both", expand=True, padx=10, pady=4)
        ctk.CTkLabel(lf, text="Status Log:").pack(anchor="w", padx=10, pady=(8, 2))
        self.log = ctk.CTkTextbox(lf, height=10, wrap="word")
        self.log.pack(fill="both", expand=True, padx=10, pady=(0, 8))
        self.log.configure(state="disabled")

        pf = ctk.CTkFrame(self.right)
        pf.pack(fill="x", padx=10, pady=(4, 8))
        self.progress = ctk.CTkProgressBar(pf)
        self.progress.set(0)
        self.progress.pack(fill="x", padx=10, pady=(10, 6))
        self.save_btn = ctk.CTkButton(pf, text="Save & Reboot Pico", command=self.save_thread)
        self.save_btn.pack(fill="x", padx=10, pady=(4, 10))

    def bottom_bar(self):
        bar = ctk.CTkFrame(self.root, height=28, corner_radius=0)
        bar.pack(fill="x", side="bottom")
        self.status = tk.StringVar(value="Ready (v7.0 Linux).")
        ctk.CTkLabel(bar, textvariable=self.status, anchor="w").pack(side="left", padx=10)
        ctk.CTkLabel(bar, text="Advanced Macro Edition — Linux", anchor="e").pack(side="right", padx=10)

    def save_thread(self):
        self.save_btn.configure(state="disabled")
        self.refresh_btn.configure(state="disabled")

        snapshot = {
            "s_vol":   self._safe_int(self.sens_vol.get(), 2),
            "s_scr":   self._safe_int(self.sens_scr.get(), 1),
            "s_mouse": self._safe_int(self.sens_mouse.get(), 4),
            "p1":      json.loads(json.dumps(self.profile_vars.get(1, {}))),
            "p2":      json.loads(json.dumps(self.profile_vars.get(2, {}))),
            "p3":      json.loads(json.dumps(self.profile_vars.get(3, {}))),
        }
        threading.Thread(target=self._save_and_reboot, args=(snapshot,), daemon=True).start()
        self.animate_progress()

    def refresh_thread(self):
        threading.Thread(target=self._refresh, daemon=True).start()

    def animate_progress(self):
        def step():
            val = self.progress.get() + 0.03
            if val > 0.9:
                val = 0.1
            self.progress.set(val)
            if str(self.save_btn.cget("state")) == "disabled":
                self.root.after(120, step)
            else:
                self.progress.set(1.0)
                self.root.after(700, lambda: self.progress.set(0))
        step()

    def log_add(self, text):
        def _update():
            self.log.configure(state="normal")
            self.log.insert("end", f"{time.strftime('%H:%M:%S')} — {text}\n")
            self.log.see("end")
            self.log.configure(state="disabled")
        self.root.after(0, _update)

    def set_status(self, text):
        self.root.after(0, lambda: self.status.set(text))


    def _save_and_reboot(self, snap):

        try:
            self.set_status("Finding CIRCUITPY...")
            self.log_add("Searching for drive...")
            drive = find_circuitpy_drive()

            if not drive:
                self.log_add("CIRCUITPY not found.")
                self.log_add("  Is the Pico plugged in?")
                self.log_add("  Diagnose:  lsblk -o NAME,LABEL,MOUNTPOINT")
                self.set_status("Error: drive not found")
                self.root.after(0, lambda: messagebox.showerror(
                    "Drive Not Found",
                    "CIRCUITPY drive not found.\n\n"
                    "Make sure the Pico is plugged in and mounted.\n\n"
                    "Diagnose with:\n    lsblk -o NAME,LABEL,MOUNTPOINT"
                ))
                return

            self.log_add(f"Drive found: {drive}")
            json_path = os.path.join(drive, "profiles.json")

            s_vol   = snap["s_vol"]
            s_scr   = snap["s_scr"]
            s_mouse = snap["s_mouse"]
            p1      = snap["p1"]
            p2      = snap["p2"]
            p3      = snap["p3"]

            cur_prof = 1
            if os.path.exists(json_path):
                try:
                    with open(json_path, "r", encoding="utf-8") as f:
                        cur_prof = json.load(f).get("current_profile", 1)
                except Exception:
                    pass

            cfg = {
                "current_profile":    cur_prof,
                "sensitivity_volume": s_vol,
                "sensitivity_scroll": s_scr,
                "sensitivity_mouse":  s_mouse,
                "profiles":           [p1, p2, p3],
            }


            with open(json_path, "w", encoding="utf-8") as f:
                json.dump(cfg, f, indent=2, ensure_ascii=False)
                f.flush()
                os.fsync(f.fileno())

            self.save_gui_settings(p1, p2, p3, s_vol, s_scr, s_mouse)
            self.log_add("File saved and flushed to device.")
            self.set_status("Finishing write...")
            time.sleep(0.5)

            port = find_pico_serial_port_for_reboot()
            if port:
                self.root.after(0, lambda: self.reboot_port_label.configure(
                    text=f"Reboot port: {port}"))
                self.log_add(f"Rebooting via {port}...")
                self.set_status("Sending reboot...")
                result = send_reboot_command(port)

                if result == "permission_error":
                    self.log_add("FAILED: Permission denied on serial port.")
                    self.log_add("  Fix:  sudo usermod -aG dialout $USER  (then log out/in)")
                    self.set_status("Permission error — see log")
                    self.root.after(0, lambda: messagebox.showerror(
                        "Serial Permission Error",
                        f"Cannot open {port}: Permission denied.\n\n"
                        "Your user is not in the 'dialout' group.\n\n"
                        "Run this in a terminal, then log out and back in:\n\n"
                        "    sudo usermod -aG dialout $USER\n\n"
                        "Settings were saved. Unplug and replug the Pico to apply them now."
                    ))
                elif result is True:
                    self.log_add("Reboot command sent.")
                    self.set_status("Complete.")
                    self.root.after(0, lambda: messagebox.showinfo("Success", "Saved & Rebooted!"))
                else:
                    self.log_add("Failed to send reboot command.")
                    self.set_status("Manual reboot required.")
                    self.root.after(0, lambda: messagebox.showwarning(
                        "Warning",
                        "Saved, but failed to send the reboot command.\n"
                        "Unplug and replug the Pico to apply settings."
                    ))
            else:
                self.log_add("Serial port not found.")
                self.log_add("  Check:  ls /dev/ttyACM* /dev/ttyUSB*")
                self.set_status("Complete.")
                self.root.after(0, lambda: messagebox.showinfo(
                    "Success",
                    "Settings saved!\n"
                    "The Pico will apply them on its next reboot.\n\n"
                    "(Serial port not found — unplug and replug the Pico.)"
                ))

        except PermissionError as e:
            self.log_add(f"Permission error writing to drive: {e}")
            self.set_status("Permission error — drive write failed")
            self.root.after(0, lambda: messagebox.showerror(
                "Write Permission Error",
                f"Could not write to the CIRCUITPY drive:\n{e}\n\n"
                "The drive may be mounted read-only.\n"
                "Unplug and replug the Pico, then try again."
            ))
        except Exception as e:
            self.log_add(f"Error: {e}")
            self.set_status("Write Error")
            self.root.after(0, lambda: messagebox.showerror("Error", str(e)))
        finally:

            try:
                self.root.after(0, lambda: self.save_btn.configure(state="normal"))
                self.root.after(0, lambda: self.refresh_btn.configure(state="normal"))
            except Exception:
                pass

    def _refresh(self):
        self.set_status("Searching...")
        drive = find_circuitpy_drive()
        self.log_add(f"Drive: {drive if drive else '-- (not found)'}")
        if not drive:
            self.log_add("  Diagnose:  lsblk -o NAME,LABEL,MOUNTPOINT")
        port = find_pico_serial_port_for_reboot()
        self.root.after(0, lambda: self.reboot_port_label.configure(
            text=f"Reboot port: {port if port else '--'}"))
        if not port:
            self.log_add("  Check serial:  ls /dev/ttyACM* /dev/ttyUSB*")
        self.set_status("Ready.")

  
    @staticmethod
    def _safe_int(v, default):
        try:
            return int(v)
        except Exception:
            return default

    def save_gui_settings(self, p1, p2, p3, sv, ss, sm):
        data = {
            "profile1": p1, "profile2": p2, "profile3": p3,
            "sensitivity_volume": sv, "sensitivity_scroll": ss, "sensitivity_mouse": sm,
        }
        try:
            with open("configurator_settings.json", "w", encoding="utf-8") as f:
                json.dump(data, f, indent=4, ensure_ascii=False)
        except Exception as e:
            self.log_add(f"Error saving GUI settings: {e}")

    def load_gui_settings(self):

        def _noop():
            return {"type": "simple", "action": "nothing"}

        def _fresh_base():
            return {k: _noop() for k in _ALL_GESTURE_KEYS}

        p1 = {**_fresh_base(),
              "cw":         {"type": "simple", "action": "volume_up"},
              "ccw":        {"type": "simple", "action": "volume_down"},
              "click":      {"type": "simple", "action": "mute"},
              "long_press": {"type": "simple", "action": "next_profile"}}
        p2 = {**_fresh_base(),
              "cw":    {"type": "simple", "action": "scroll_up"},
              "ccw":   {"type": "simple", "action": "scroll_down"},
              "click": {"type": "simple", "action": "play_pause"}}
        p3 = {**_fresh_base(),
              "cw":          {"type": "simple", "action": "mouse_scroll_v_pos"},
              "ccw":         {"type": "simple", "action": "mouse_scroll_v_neg"},
              "click":       {"type": "simple", "action": "mouse_click_middle"},
              "cw_shifted":  {"type": "simple", "action": "mouse_scroll_h_pos"},
              "ccw_shifted": {"type": "simple", "action": "mouse_scroll_h_neg"}}
        d = {"profile1": p1, "profile2": p2, "profile3": p3,
             "sensitivity_volume": 2, "sensitivity_scroll": 1, "sensitivity_mouse": 4}

        try:
            with open("configurator_settings.json", "r", encoding="utf-8") as f:
                loaded = json.load(f)

            p1_loaded = loaded.get("profile1", {})
            if isinstance(p1_loaded.get("cw"), str):
                self.log_add("Old v1.0 config detected — migrating to v4.0...")
                d = self._migrate_v1_to_v4(loaded)
            elif "cw_shifted" not in p1_loaded:
                self.log_add("v2.0 config detected — migrating to v4.0...")
                d.update(loaded)
                for i in (1, 2, 3):
                    for k in ("cw_shifted", "ccw_shifted", "double_click", "triple_click"):
                        d[f"profile{i}"].setdefault(k, {"type": "simple", "action": "nothing"})
            elif "double_click" not in p1_loaded:
                self.log_add("v3.0 config detected — migrating to v4.0...")
                d.update(loaded)
                for i in (1, 2, 3):
                    for k in ("double_click", "triple_click"):
                        d[f"profile{i}"].setdefault(k, {"type": "simple", "action": "nothing"})
            else:
                d.update(loaded)
                self.log_add("Loaded v4.0+ (Advanced Macro) config.")
        except FileNotFoundError:
            self.log_add("No settings file found — loading defaults.")
        except Exception as e:
            self.log_add(f"Error loading settings: {e} — loading defaults.")
        return d

    def _migrate_v1_to_v4(self, v1):
        result = {
            "sensitivity_volume": v1.get("sensitivity_volume", 2),
            "sensitivity_scroll": v1.get("sensitivity_scroll", 1),
            "sensitivity_mouse":  4,
        }
        for i in (1, 2, 3):
            old = v1.get(f"profile{i}", {})
            new = {k: {"type": "simple", "action": old.get(k, "nothing")}
                   for k in ("cw", "ccw", "click", "long_press")}
            for k in ("cw_shifted", "ccw_shifted", "double_click", "triple_click"):
                new[k] = {"type": "simple", "action": "nothing"}
            result[f"profile{i}"] = new
        return result


if __name__ == "__main__":
    root = ctk.CTk()
    app  = MultiKnobConfiguratorModern(root)
    root.mainloop()
